API Interactivity
DarkxDev/Leaderboard-App pull request #2
Opened 2023-02-01 22:05 UTC by DarkxDev

- Create a new game.
- Saving ID of the game returned by the API.
- Implemented a "Refresh" button that will get all scores for the created game.
- Implemented a "Submit" button.

2023-02-01 22:33 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @DarkxDev , 
I'm Andres.

While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 
✅ Very Organized and clean code! 🥇 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please always make sure that all the links in your README are working, currently, your LICENSE link is broken because you don't have one. Microverse suggests using the MIT license for your projects, but feel free to choose the one that you like! You can follow [GitHub's official docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to achieve this requirement. 🤓 🔧 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 22:33 UTC, anagudelogu commented on src/index.js
> +  }
- [ ] You did a brilliant job working on this milestone, your code is clean and very readable, kudos for that! 💯 Also, I noticed that you used this exact same code inside the refresh button listener, remember that part of keeping the code clean and simple is to use the DRY principle, "Don't Repeat Yourself". I think it would be better to fire this logic from a better listener, for example, on window load:

```js
window.addEventListener("load", () => {
    if (!localStorage.getItem('gameID')) {
    const gameID = await createGame();
    localStorage.setItem('gameID', gameID);
  }
});
```

So once the content has loaded, this listener is going to check for the existence of the `gameID` key in the localStorage and decide whether or not to create a new game, so you make sure that when the user clicks either the `refresh` or the `create score` buttons, a game already exists, avoiding that repeated operation! 🤓 🔧

2023-02-02 01:08 UTC, DarkxDev commented on src/index.js
> +  }
Oh, you're right, that's a good idea, thank you!

2023-02-02 01:34 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @DarkxDev , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 02:37 UTC, merged